#!/bin/sh
set -e

update-alternatives --install /usr/bin/x-terminal-emulator \
  x-terminal-emulator /usr/bin/terminology 50 --slave \
  /usr/share/man/man1/x-terminal-emulator.1.gz x-terminal-emulator.1.gz \
  /usr/share/man/man1/terminology.1.gz

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

exit 0